export {default as dice} from './dice.js'
export {default as logn} from './logn.js'
export {default as norm} from './norm.js'
export {default as step} from './step.js'
export {default as uniform} from './uniform.js'
export {default as weibull} from './weibull.js'
